# Generated by Django 4.2.26 on 2026-01-19 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(help_text='Matrícula', max_length=20, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_manufactured', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('first_class_seats', models.IntegerField(default=0)),
                ('business_class_seats', models.IntegerField(default=0)),
                ('economy_class_seats', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operacional'), ('MAINTENANCE', 'En Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de Servicio'), ('RETIRED', 'Retirada')], default='OPERATIONAL', max_length=20)),
                ('flight_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_flights', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircrafts', to='airlines.airline')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'ordering': ['airline', 'registration'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Rutinario'), ('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('INSPECTION', 'Inspección'), ('REPAIR', 'Reparación'), ('OVERHAUL', 'Revisión General')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('findings', models.TextField(blank=True, help_text='Hallazgos durante el mantenimiento')),
                ('actions_taken', models.TextField(blank=True, help_text='Acciones realizadas')),
                ('technician', models.CharField(max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('parts_used', models.TextField(blank=True, help_text='Partes y materiales utilizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='maintenance.aircraft')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['aircraft', 'status'], name='maintenance_aircraf_24c2d0_idx'), models.Index(fields=['-scheduled_date'], name='maintenance_schedul_057fc5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['registration'], name='maintenance_registr_391321_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['status'], name='maintenance_status_3244db_idx'),
        ),
    ]
