# Generated by Django 4.2.26 on 2025-11-25 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Pasaporte'), ('ID_CARD', 'Cédula/DNI'), ('DRIVER_LICENSE', 'Licencia de Conducir')], default='PASSPORT', max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('document_expiry', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=50)),
                ('preferred_seat', models.CharField(blank=True, choices=[('WINDOW', 'Ventana'), ('AISLE', 'Pasillo'), ('MIDDLE', 'Medio')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
