# Generated by Django 4.2.26 on 2025-11-25 22:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, help_text='Número de reserva generado automáticamente', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=16)),
                ('passenger_name', models.CharField(max_length=160)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(blank=True, max_length=20)),
                ('passenger_document', models.CharField(blank=True, help_text='Número de pasaporte o documento de identidad', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=160)),
                ('passenger_document', models.CharField(max_length=50)),
                ('passenger_age', models.PositiveIntegerField(blank=True, help_text='Edad del pasajero', null=True)),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adulto'), ('CHILD', 'Niño'), ('INFANT', 'Infante')], default='ADULT', max_length=10)),
                ('seat_number', models.CharField(blank=True, help_text='Número de asiento (ej: 12A, 23F)', max_length=10)),
                ('checked_bags', models.PositiveIntegerField(default=0, help_text='Número de maletas documentadas')),
                ('carry_on_bags', models.PositiveIntegerField(default=1, help_text='Número de maletas de mano')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('baggage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='invoices.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.flight')),
            ],
            options={
                'verbose_name': 'Detalle de Reserva',
                'verbose_name_plural': 'Detalles de Reserva',
                'indexes': [models.Index(fields=['booking', 'flight'], name='invoices_bo_booking_1b87cc_idx')],
                'unique_together': {('flight', 'seat_number')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='invoices_bo_booking_9ecfab_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='invoices_bo_user_id_e4dac3_idx'),
        ),
    ]
