# Generated by Django 4.2.26 on 2025-11-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código IATA de la aerolínea (ej: AA, UA, DL, AM)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Número de vuelo (ej: AA100, AM456)', max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Precio base del vuelo en USD', max_digits=10)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('total_seats', models.PositiveIntegerField(default=180)),
                ('flight_class', models.CharField(choices=[('ECONOMY', 'Económica'), ('PREMIUM_ECONOMY', 'Económica Premium'), ('BUSINESS', 'Ejecutiva'), ('FIRST', 'Primera Clase')], default='ECONOMY', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('BOARDING', 'Abordando'), ('DEPARTED', 'Despegado'), ('IN_FLIGHT', 'En Vuelo'), ('ARRIVED', 'Arribado'), ('CANCELLED', 'Cancelado'), ('DELAYED', 'Retrasado')], default='SCHEDULED', max_length=20)),
                ('aircraft_type', models.CharField(blank=True, help_text='Tipo de aeronave (ej: Boeing 737, Airbus A320)', max_length=50)),
                ('gate', models.CharField(blank=True, help_text='Puerta de embarque', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='catalog.airline')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='warehouses.airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='warehouses.airport')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ('-departure_time',),
                'indexes': [models.Index(fields=['flight_number', 'departure_time'], name='catalog_fli_flight__e8abc6_idx'), models.Index(fields=['origin_airport', 'destination_airport'], name='catalog_fli_origin__c52d83_idx'), models.Index(fields=['status'], name='catalog_fli_status_791f2b_idx')],
            },
        ),
    ]
