# Generated by Django 4.2.26 on 2025-11-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código IATA del aeropuerto (ej: JFK, LAX, MEX, CDG)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('timezone', models.CharField(blank=True, help_text='Zona horaria del aeropuerto (ej: America/New_York)', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.IntegerField(blank=True, help_text='Elevación en metros sobre el nivel del mar', null=True)),
                ('website', models.URLField(blank=True)),
                ('is_international', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='warehouses__code_999d31_idx'), models.Index(fields=['city', 'country'], name='warehouses__city_5c076d_idx')],
            },
        ),
    ]
