# Generated by Django 4.2.26 on 2026-01-15 00:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '__first__'),
        ('passengers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_class', models.CharField(choices=[('ECONOMY', 'Económica'), ('PREMIUM_ECONOMY', 'Premium Económica'), ('BUSINESS', 'Ejecutiva'), ('FIRST', 'Primera Clase')], default='ECONOMY', max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('checked_baggage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('carry_on_baggage', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Tarjeta de Crédito'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_requests', models.TextField(blank=True)),
                ('meal_preference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='passengers.passenger')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['booking_code'], name='bookings_bo_booking_51e913_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['-booking_date'], name='bookings_bo_booking_d0de6b_idx')],
            },
        ),
    ]
