# Generated by Django 4.2.26 on 2026-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'PAID'])), fields=('passenger', 'flight'), name='unique_active_booking_per_passenger_flight'),
        ),
    ]
